name: querell
version: 0.1.0.0
github: "phisn/querell"
language: GHC2021

dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - transformers

library:
  source-dirs: src

executables:
  querell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - querell

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
